apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-robotoh-io
  namespace: traefik
spec:
  secretName: wildcard-robotoh-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - robotoh.io
    - "*.robotoh.io"