---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBj9rApMmFYOoJThHOHHftRc5fXI6DuHUAaCfcZHnQwPr/X3xhO6mjCsVnd+R5LCepeodTPxfCLoiWmqHDxHXzsE30h5ii3XubOrG+XOaIEgYBeO4gGi6SJb8cDuH/cEGJMITmyMmjzeL5aginUEO6JEVJHMiKxKcIwoKZVNvfAwX7NzH1U6sYE6/NpzG5TG+QhX6cJREM14VB+t4Kcl7nvw1NpcdJdBuC695LTDbaBhq7/5ZdO/4wiRs34VglMIHGHYTXa5a+c2zRpMN+FbuHwg/fHkNWmZL2nLPAg1Q0hjNOwS6pg+cwx0KowhnY4qh+2Yi43dXspIUl/ElQVODvMcVQixaiIZlvNIq6wBFVv5Y7T0W8Lyqq4g9T48QYYKWs8E48WCvoKgOoKQleDwIHywVLX4AZSezmgwphIwdUdObmG5nPJrSdGQlecYsrrGYywnTwSEIV+cg7R12MXHAwvIHSkMRBjZVFIWxEmXOFbPiFq0sovnVnVXDdyeLd0CAiud4x396ofuTzCWqXIuZSLZ0k3qxDaEdWjv8k5QTet9JTzS9FYksd4f14gAjicRxssiOJtS9MYMNKk1rtmVDYF22CdoinSuZAL4QEIvJo5dlTdbimr27yIwYRvpbV5bbyF9r3lbnRvGnI7aYRC6bLaUr01ZHvD678S4EFSGMzEqXHYdd6codTzZm57txmWGw/JUJyzRNCGH0Hr04yOTencBBohlag4CiU1WyuipDknpFTcn89TRLcOGVcMHNorxKpH6lsMlx53ixOKTLzE2kaDBPjfqNj/nrVgj+RqRGJdnJT68obuGsq09TvZsE2c64Hw7w/GR1rs3LPKDOmBl81kMDCYwnooigYXZ/qBKRPHlzY03P4xJXvUgImrRtqM03WvnBWZEbtPPkNFFNf+ZQCGqhBcXqQuVeNDzx6Gf4PHj/eOC53Nyk9d
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
