---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCctTUFr6hsetgm1761RO5RP7/4e5EqaecbXifxsAzdYPAkvLGYzgjB74LQmGiFf36BYA8yAPEgvoZUa9kFyvW4B2HprPFoVwouY06JVM9HFutSkATAM4qt9gJJDnvrG65wDFPL+F/+y8EhgriexaaMeVMjimTDuZivg2Yy/j40yUohLcbjE+ECRgMz3B6b21i31lzEpCCtgvoyh1FwMw5ymXwZyI6MW9XGm8rkWvCleKxTge2RorUlTurj+Y4NMSde1ay6Ew0jw6KqGA5a+uDWjhYqnbCHUySD8L5XD1nz0l0x/Zf60mXcytL51Z6DbldlyMLRtIxEPffK5hhQ1FGWGT6dwfGD76qH8FZEj7Ee4FZyPBBsf0DH4j2GFgIXC1TAUIeC8lDLIYyY41csd8o7bympgZwdlNsuVI3sH+GmYQb8RJDgHb+P/vJ2OiOwQKlWUiTaYbfiSYvPx7eBmq8oUdPRQE9QjMqGu3kVxDDwodpqj89pr+1AEx9CMGpNcBgH1STS/DxYIZBWd4GSZ1D62OJ6nqEMRuyBLGtuDwcFpeBVReaPWraiuwQZCnTRRVJ1jYRuwAK8y6y35rry6fiDrKQ77eFZZbifq3Zm3HiCCqE2W5vOQP2nQsEIstOwkLb/mzem74iuFVqUl2rHHvIdIys9rYwfDWDb+B2hzFeCrCavIflmHIdp1g3Jw0DNQ+Y=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-discord
      namespace: monitoring
