---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCizuQ/k4srUSuxcmR0oykJyM8B2j60RuB2AzKi2k1Z7qGYLJZra13tuQvByMe3MZlMuPOYZNW0CM2lZi0U+2maRjLLX8obA+BmkukBYvtZfalryUMpLVm5azc3pKQoatBS65eBNVdhmGwE7FpQa0GhjfKiGkeV94JFIDjcwI7FjbJm8fb1dBAdCQKJM1f7PsBroOgiNWO/E5lu6zBsnYRSBUtj7jIlSUT6So6GCxa0+hoHjcuaozcRmGnE7Tdm29ejfSg/7/siiN/kD5gfYLQto9wBUT55Akc+/c11tEsiOSbdXDbcLzC4ee/cC+G5t86rB6UBEd2KuJrOSGDs6+8jOmfypT4ughmfPRxlZEowjgLtflDMmM+Li0ihMdZjTjhXNeMRpaVWvGb6EjVQSBNsBPVUMu8AUsVKWGYMxH8QK2BvzFqe/YUL5miSZNv16Dls7RP4/nqDvV+t0hvol8TziDVtPsU5P/54knC/f5M3GWVe1/m2nb48MVR6hyF9Yp7J9HqwI0gUPNjBQ8myMfB6dVujKjTQkmRaWdkHKrfCyRwuU89Jqmx4L5Bk/dhKnUyTG9Jf7Zz92QP+NLlEoIZptJYT5x0wXj/tvJzOTlrtw6aPyrwt1TWM0lwvnQPUrbBA86bg2Sr5ZbwUItKMiBnNxepn1sOMNlBQ+x0mZFfL80qSLYc5Eg+WqubMe0yh39IJHBPQ00ooMB5CyyWKGwL0CKLrx7+mdtNk9/ItuI+yzbnDV7o9TdyaOBPovTi4JA5KOW3gRCmTwz43v2IvWeiMkPQI8FzQ5z4bxIKHF99Hknonnktf6qbtYJyk/2BmSnsKuruAc+djllt0d9O7ukn/l4cnsTav28hR2bzJ79QuCA==
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
