---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDV/8ckFYKyjRTMaDIcorx6PAxaPNLGqUYgAHUDn9UfFln4gExbxagwk23Ez6XuR993D5vjaFc15oQVlXdV7xEm/9Tebj1SS4WbcqIQth0CZWXjpdzhufd6CQvJKz5GZhBGBT3fQppfwrr3NoG6ndCx/2y1DvN+q1YRVEhrlWJjuoHsviqHdJORqtHBJObhce+QCaqlDXpwqhNzq0zJmHHvwZZ4LoBZg1vipnVAWsiEq3O+ULEI+Rz7mLwnqn0tzZuwADtRZUhJOx1MvqhSXNnqM4+g+YGhJIShdNl9HPLTHFyIeNQP0rSJMpyhjOUgz+OZYdKnr8d8VBzsAjS66P4yYBszs9mzXsVjTQVwSTELNwwED5eAh/BoiW5olFjyb43TTAg6NlQNCL+L2BzUlsZNJHu2uiR2wwftT9MF4sGjw/AMpovzKvbhPfqrPjcnegSRFvfGzV0daRO2oin0rXEUKAAwrRRwYmPVaDJgjZWnsmuqa0oWKbEjftEmaZpajbqD0AnV0rxaiYODFFaYnqQcMVCiy+zeK/nhWVNlZAJPgY1dz6u/tgM55G0OUr4IR0CuiZvqkqviL3p6jvXhop8JZALQqRa9nwEXffpC1Jo2TRGwiC51/N+vu45fGUgbD+rDFzRmrLA85l01k9fbPDInDD3Otb3uoh1siFP7RZL96o+ZRj+XiP6NlAP39Z4kltIR1gutco3rzHg+FDD7wU7JgPJ3SPh6DYtePuVwUBbXCA==
    admin-user: AgBv0WHic6v4PDyAQEHqomD6JSVy2Pa/Mk2foFy2ZSJR1uv3ORIDpwirSRA45zcTdQ5hKp8F0fsHwVKpAiCA2QEVTpR1BM/skPqxnU48PDA5lyHT55I5eHdkDyqhnVQbdxOa0tAm4jQyl2yKy8v8Z+w1X+sdXteXzqRsw2jPdx8JmzO5snXxZCN31ZyTf6msZvCFJjnEkC/MVCKFswpB40TLlwgGLO9NNGs3nEY3Gqj7dWZKh4u4IxUBCafEoWVk1GxzLBorLSRbrBC8rY127dwpI1/Fo1T8NpUYumZgDdxCny7Iq9jjAV12C4rD8iU1pmI9xaPMtcq5CGxKU3uWpCGUryANpPPliZQxcxIep8+aLm+Ts42oppiCplvAQahhg545YtMZlrTxFBvNTVI44iDE+UHtP93ZdYq00V3ppBm2yVRKJw8wVpSs3+v4f0QsBwj4D0VbZ0Kyscj29H5LCTo65p7p5/TMjDbTntnJDrst888QwigYI4npgNGjf08K7DnFDK52mJhj6FI2mhgtfKb3qdO0q2+PfO7fTa/4Qt9yh5+BcCMwK3Xas5zhgAWJ94k8ZL32CcKV8EexMhqXrkXzyJnApomABCWf1QOBULaKpq6LpjTsvlCfIvYrjT1gGmXdVXM8Ee1qXyG1Y3pRFTBx69HtTuSZTJ9AAl70gcEN0tQZI4V30GDHVHowbeLacFZCUePFNw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
