apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-network
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://github.com/monospaced-dev/homelab-platform.git
    targetRevision: main
    path: infrastructure/kyverno-network
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true