apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.6.0
    helm:
      valuesObject:
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: "10.20.10.1"
        ingressClass:
          enabled: true
          isDefaultClass: true
        providers:
          kubernetesIngress:
            enabled: true
          kubernetesCRD:
            enabled: true
        metrics:
          prometheus:
            serviceMonitor:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/audit: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true